<x-layouts.public
    title="Terms of Service — FleetQ"
    description="Read the terms and conditions governing your use of the FleetQ platform."
>
    <x-landing.nav />

    <article class="mx-auto max-w-4xl px-6 py-16 sm:py-24 lg:px-8">
        <div class="prose prose-gray max-w-none prose-headings:font-bold prose-h1:text-3xl prose-h1:sm:text-4xl prose-h2:text-xl prose-h2:sm:text-2xl prose-h2:mt-10 prose-h2:border-t prose-h2:border-gray-200 prose-h2:pt-8 prose-a:text-primary-600 prose-a:no-underline hover:prose-a:underline">
            <p class="text-sm text-gray-500">Last updated: 22 February 2026</p>

            <h1>Terms of Service</h1>

            <h2>1. Agreement to Terms</h2>
            <p>By accessing or using FleetQ (the "Service") operated by PriceX Ltd. ("we," "us," or "our"), you agree to be bound by these Terms of Service. If you do not agree, you may not use the Service.</p>

            <h2>2. Description of Service</h2>
            <p>FleetQ is an AI Agent Mission Control Platform that enables you to create, orchestrate, and manage AI agents, workflows, and experiments. The Service is available as:</p>
            <ul>
                <li><strong>Community Edition:</strong> Free, open-source, self-hosted under the MIT License</li>
                <li><strong>Cloud Edition:</strong> Managed SaaS with subscription plans (Free, Starter, Pro, Enterprise)</li>
            </ul>

            <h2>3. Account Registration</h2>
            <p>To use the Service, you must create an account. You agree to:</p>
            <ul>
                <li>Provide accurate and complete registration information</li>
                <li>Maintain the security of your account credentials</li>
                <li>Promptly notify us of any unauthorized access</li>
                <li>Accept responsibility for all activity under your account</li>
            </ul>

            <h2>4. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul>
                <li>Use the Service for any unlawful purpose</li>
                <li>Violate any applicable laws or regulations</li>
                <li>Attempt to gain unauthorized access to the Service or its systems</li>
                <li>Interfere with or disrupt the Service's infrastructure</li>
                <li>Use the Service to send spam, phishing, or other unsolicited communications</li>
                <li>Use AI agents to generate harmful, deceptive, or illegal content</li>
                <li>Circumvent rate limits, budget controls, or other safety mechanisms</li>
                <li>Reverse-engineer, decompile, or disassemble the Service (except as permitted by the MIT License for the Community Edition)</li>
            </ul>

            <h2>5. AI Processing and BYOK</h2>
            <p>FleetQ integrates with third-party AI providers (Anthropic, OpenAI, Google). You acknowledge that:</p>
            <ul>
                <li>When using BYOK (Bring Your Own Key), you are responsible for compliance with each AI provider's terms of service</li>
                <li>AI-generated outputs may be inaccurate and should not be relied upon without human review</li>
                <li>You are responsible for the content of prompts sent to AI providers</li>
                <li>We are not liable for any actions taken based on AI-generated outputs</li>
            </ul>

            <h2>6. Intellectual Property</h2>
            <ul>
                <li><strong>Your Content:</strong> You retain all rights to data and content you upload or create using the Service</li>
                <li><strong>AI Outputs:</strong> Outputs generated by AI agents using your prompts and data belong to you, subject to the AI provider's terms</li>
                <li><strong>Community Edition:</strong> Licensed under the MIT License</li>
                <li><strong>Cloud Edition:</strong> The Service and its proprietary features remain our intellectual property</li>
            </ul>

            <h2>7. Subscription and Billing (Cloud Edition)</h2>
            <ul>
                <li>Paid plans are billed monthly in EUR via Stripe</li>
                <li>You can upgrade, downgrade, or cancel at any time</li>
                <li>Upgrades take effect immediately; downgrades at the next billing cycle</li>
                <li>We reserve the right to change pricing with 30 days' notice</li>
                <li>Refunds are handled in accordance with applicable consumer protection laws</li>
            </ul>

            <h2>8. Usage Limits</h2>
            <p>Each subscription plan includes usage limits (agent runs, outbound sends, team members, etc.). When limits are reached:</p>
            <ul>
                <li>You will receive alerts at 80% and 100% of your usage</li>
                <li>Exceeding limits may pause new operations until the next billing cycle</li>
                <li>You can upgrade your plan to increase limits</li>
            </ul>

            <h2>9. Data Protection</h2>
            <p>We process your data in accordance with our <a href="{{ route('legal.privacy') }}">Privacy Policy</a>. For the Cloud Edition, a Data Processing Agreement (DPA) is available upon request at <a href="mailto:privacy@pricex.app">privacy@pricex.app</a>.</p>

            <h2>10. Service Availability</h2>
            <ul>
                <li>We aim for high availability but do not guarantee uninterrupted service</li>
                <li>Scheduled maintenance will be communicated in advance when possible</li>
                <li>We are not liable for downtime caused by factors beyond our control</li>
            </ul>

            <h2>11. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law:</p>
            <ul>
                <li>The Service is provided "as is" without warranties of any kind</li>
                <li>We are not liable for indirect, incidental, or consequential damages</li>
                <li>Our total liability shall not exceed the amount paid by you in the 12 months preceding the claim</li>
                <li>For the Community Edition (free, self-hosted), the Service is provided without any warranty or liability</li>
            </ul>

            <h2>12. Termination</h2>
            <ul>
                <li>You may terminate your account at any time</li>
                <li>We may suspend or terminate your account for violation of these Terms</li>
                <li>Upon termination, your data will be deleted within 30 days (subject to legal retention requirements)</li>
            </ul>

            <h2>13. Governing Law</h2>
            <p>These Terms are governed by the laws of the Republic of Bulgaria. Any disputes shall be resolved by the competent courts in Plovdiv, Bulgaria, without prejudice to your rights under mandatory consumer protection laws of your jurisdiction.</p>

            <h2>14. Changes to These Terms</h2>
            <p>We may update these Terms with 30 days' notice via email or in-app notification. Continued use after changes constitutes acceptance.</p>

            <h2>15. Contact</h2>
            <ul>
                <li><strong>Email:</strong> <a href="mailto:privacy@pricex.app">privacy@pricex.app</a></li>
                <li><strong>Address:</strong> PriceX Ltd., 1 Petyofi street, Plovdiv, Bulgaria</li>
            </ul>
        </div>
    </article>

    <x-landing.footer />
</x-layouts.public>
