<?php

return [

    'content-marketing' => [
        'meta_title' => 'AI Agents for Content Marketing Automation | FleetQ',
        'meta_description' => 'Automate content research, drafting, and publishing with AI agent crews. Ship 10x more content without growing your team. Start free with FleetQ.',
        'keywords' => 'ai agents content marketing, automate blog writing, ai content pipeline, content automation ai, ai writing crew',
        'title_short' => 'Content Marketing',
        'icon_color' => 'primary',
        'accent' => 'border-t-primary-400',
        'icon_bg' => 'bg-primary-50',
        'icon_text' => 'text-primary-600',
        'heading' => 'Automate Content Creation at Scale with AI Agent Crews',
        'subheading' => 'Deploy a crew of specialised AI agents that research topics, write drafts, apply your brand voice, and publish — while your team focuses on strategy.',
        'pain_points' => [
            'Content briefs sit in a backlog for weeks while writers are stretched across projects.',
            'Research takes longer than writing — each article requires hours of manual information gathering.',
            'Inconsistent tone and brand voice creep in when multiple writers work in parallel.',
            'Publishing workflows involve too many manual hand-offs between research, writing, editing, and scheduling.',
        ],
        'workflow_steps' => [
            ['type' => 'signal',   'label' => 'Content Brief',    'description' => 'A new brief arrives via webhook, form, or Telegram — triggering the crew.', 'color' => 'blue'],
            ['type' => 'agent',    'label' => 'Research Agent',   'description' => 'Searches the web, aggregates sources, and builds a structured research document.', 'color' => 'primary'],
            ['type' => 'agent',    'label' => 'Writer Agent',     'description' => 'Produces a full draft using your brand guidelines and the research context.', 'color' => 'primary'],
            ['type' => 'agent',    'label' => 'Editor Agent',     'description' => 'Reviews for tone, SEO keywords, readability, and structure. Returns a polished draft.', 'color' => 'violet'],
            ['type' => 'approval', 'label' => 'Human Review',     'description' => 'Optional approval gate — your editor reviews before anything goes live.', 'color' => 'amber'],
            ['type' => 'output',   'label' => 'Publish Agent',    'description' => 'Formats and publishes to your CMS, blog, or social channels automatically.', 'color' => 'green'],
        ],
        'metrics' => [
            ['number' => '10×',  'label' => 'Content output',       'description' => 'Teams ship dramatically more content with the same headcount.'],
            ['number' => '80%',  'label' => 'Less manual research',  'description' => 'Research Agent handles information gathering end to end.'],
            ['number' => '100%', 'label' => 'Brand consistency',     'description' => 'A shared style guide skill ensures every piece matches your voice.'],
        ],
        'faqs' => [
            ['question' => 'How does the Research Agent find information?', 'answer' => 'The Research Agent uses web search tools and RSS connectors to find, read, and synthesise sources. You can restrict it to specific domains or knowledge bases.'],
            ['question' => 'Can I define my own brand voice guidelines?', 'answer' => 'Yes. Create a "Brand Voice" skill with your guidelines and attach it to the Writer and Editor agents. Every piece they produce will be checked against it.'],
            ['question' => 'Does the crew publish automatically or wait for approval?', 'answer' => 'You control this with an approval node in the workflow. You can auto-publish for lower-risk content and require human review for high-stakes pieces — or apply different rules per content type.'],
            ['question' => 'Which CMS and publishing tools are supported?', 'answer' => 'The Publish Agent can post to any system accessible via webhook, REST API, or MCP tool — including WordPress, Ghost, Contentful, Webflow, and social media platforms.'],
            ['question' => 'What happens if the Writer Agent produces poor output?', 'answer' => 'The approval gate catches this before publishing. You can also configure the Editor Agent to automatically flag drafts that fall below a quality threshold and route them back for revision.'],
        ],
        'capabilities' => [
            ['label' => 'AI Agent Crews', 'desc' => 'Coordinate multiple specialised agents in a single workflow.', 'route' => 'register'],
            ['label' => 'Signal Connectors', 'desc' => 'Trigger workflows from forms, webhooks, email, or Telegram.', 'route' => 'register'],
            ['label' => 'Skills Library', 'desc' => 'Reusable brand voice, SEO, and style guide skills.', 'route' => 'register'],
            ['label' => 'Approval Gates', 'desc' => 'Human-in-the-loop review before any content goes live.', 'route' => 'register'],
            ['label' => 'MCP Tool Integration', 'desc' => 'Connect to 120+ external tools via Model Context Protocol.', 'route' => 'register'],
            ['label' => 'Audit Trail', 'desc' => 'Full log of every agent decision and output.', 'route' => 'register'],
        ],
        'related' => ['customer-support', 'sales-automation', 'data-research'],
    ],

    'customer-support' => [
        'meta_title' => 'AI Agent Crews for Customer Support Automation | FleetQ',
        'meta_description' => 'Automate ticket triage, routing, and responses with AI agent crews. Resolve Tier-1 tickets automatically. Build with FleetQ, free and open source.',
        'keywords' => 'ai customer support automation, ticket triage ai agent, automated support workflow, ai helpdesk, customer service ai crew',
        'title_short' => 'Customer Support',
        'icon_color' => 'green',
        'accent' => 'border-t-green-400',
        'icon_bg' => 'bg-green-50',
        'icon_text' => 'text-green-600',
        'heading' => 'AI Agent Crews That Resolve Tickets Before Humans See Them',
        'subheading' => 'Automatically classify, route, and respond to incoming support tickets — so your team handles only the cases that genuinely need human judgment.',
        'pain_points' => [
            'Tier-1 repetitive tickets consume senior support engineer time that should go to complex issues.',
            'Tickets pile up overnight when your support team is offline but customers still need answers.',
            'Routing decisions are inconsistent — the same issue type ends up with different agents each time.',
            'There is no audit trail for how automated decisions were made, causing compliance headaches.',
        ],
        'workflow_steps' => [
            ['type' => 'signal',   'label' => 'Incoming Ticket',     'description' => 'A new ticket arrives from email, Zendesk, Intercom, or a webhook connector.', 'color' => 'blue'],
            ['type' => 'agent',    'label' => 'Classifier Agent',     'description' => 'Reads the ticket, assigns category, priority, and sentiment score.', 'color' => 'primary'],
            ['type' => 'agent',    'label' => 'Router Agent',         'description' => 'Checks the knowledge base and determines the right queue or escalation path.', 'color' => 'primary'],
            ['type' => 'agent',    'label' => 'Responder Agent',      'description' => 'Drafts a response for Tier-1 issues or prepares a briefing for Tier-2 escalation.', 'color' => 'violet'],
            ['type' => 'approval', 'label' => 'Human Review',         'description' => 'Optional gate for sensitive cases — a human reviews before the reply is sent.', 'color' => 'amber'],
            ['type' => 'output',   'label' => 'Close & Log',          'description' => 'Sends the reply, closes the ticket, and logs every decision in the audit trail.', 'color' => 'green'],
        ],
        'metrics' => [
            ['number' => '60%',  'label' => 'Fewer Tier-1 escalations', 'description' => 'Routine questions resolved without a human touching the ticket.'],
            ['number' => '24/7', 'label' => 'Coverage',                  'description' => 'Agents operate overnight and on weekends without extra headcount.'],
            ['number' => '100%', 'label' => 'Auditability',              'description' => 'Every decision logged with the agent\'s reasoning for compliance review.'],
        ],
        'faqs' => [
            ['question' => 'Which support platforms does this work with?', 'answer' => 'FleetQ connects to any platform accessible via webhook, email, or REST API — including Zendesk, Intercom, HelpScout, and Freshdesk. The Signal Connector handles ingestion.'],
            ['question' => 'How do I control which tickets are handled automatically?', 'answer' => 'Use conditional nodes in the workflow to route by category, priority, or sentiment. High-priority or negative-sentiment tickets can be forced through the human approval gate.'],
            ['question' => 'Can the Responder Agent use our existing knowledge base?', 'answer' => 'Yes. Attach a knowledge base search skill to the Responder Agent and it will retrieve relevant articles before drafting a response.'],
            ['question' => 'What happens when the agent is not confident in its answer?', 'answer' => 'You can set a confidence threshold in the Classifier Agent. Below that threshold, the ticket is automatically routed to the human approval queue rather than auto-responded.'],
            ['question' => 'Is there a complete log of every automated decision?', 'answer' => 'Yes. FleetQ\'s audit trail records every agent action, the inputs it received, the output it produced, and the timestamp. This is exportable for compliance reporting.'],
        ],
        'capabilities' => [
            ['label' => 'Signal Connectors', 'desc' => 'Ingest tickets from email, webhooks, Zendesk, and more.', 'route' => 'register'],
            ['label' => 'AI Agent Crews', 'desc' => 'Classifier, Router, and Responder agents working together.', 'route' => 'register'],
            ['label' => 'Approval Gates', 'desc' => 'Human review for sensitive or escalated cases.', 'route' => 'register'],
            ['label' => 'Audit Trail', 'desc' => 'Every decision logged with full reasoning for compliance.', 'route' => 'register'],
            ['label' => 'Budget Controls', 'desc' => 'Set per-run cost caps to control AI spend.', 'route' => 'register'],
            ['label' => 'AI Guardrails', 'desc' => 'PII detection and toxicity filters on every response.', 'route' => 'register'],
        ],
        'related' => ['sales-automation', 'compliance-monitoring', 'hr-recruiting'],
    ],

    'sales-automation' => [
        'meta_title' => 'AI Agents for Sales Automation & Outreach | FleetQ',
        'meta_description' => 'Build AI agent crews that research prospects, score leads, personalise outreach, and log everything to your CRM. Automate your sales pipeline with FleetQ.',
        'keywords' => 'ai sales automation, lead research agent, ai outbound sales workflow, ai prospecting, sales ai crew, automated lead generation',
        'title_short' => 'Sales Automation',
        'icon_color' => 'violet',
        'accent' => 'border-t-violet-400',
        'icon_bg' => 'bg-violet-50',
        'icon_text' => 'text-violet-600',
        'heading' => 'Build AI Agents That Research, Qualify, and Reach Out to Leads',
        'subheading' => 'From raw lead lists to personalised outreach — AI agent crews do the research and writing, while your sales team focuses on conversations that close.',
        'pain_points' => [
            'Manual prospect research takes 30–60 minutes per lead, making high-volume outbound impossible.',
            'Generic outreach templates produce low reply rates because they lack personalisation.',
            'CRM data goes stale — contact details, job titles, and company information change constantly.',
            'Your best SDRs spend half their time on research and copy, not on calls and relationships.',
        ],
        'workflow_steps' => [
            ['type' => 'signal',   'label' => 'New Lead',              'description' => 'A lead arrives from a form, CSV upload, LinkedIn scrape, or CRM webhook.', 'color' => 'blue'],
            ['type' => 'agent',    'label' => 'Research Agent',         'description' => 'Enriches the lead with company data, LinkedIn info, recent news, and tech stack.', 'color' => 'primary'],
            ['type' => 'agent',    'label' => 'Qualifier Agent',        'description' => 'Scores the lead against your ICP criteria and flags disqualified prospects.', 'color' => 'primary'],
            ['type' => 'agent',    'label' => 'Personalisation Agent',  'description' => 'Writes a tailored message referencing specific company context from the research.', 'color' => 'violet'],
            ['type' => 'approval', 'label' => 'SDR Review',             'description' => 'Your SDR reviews the draft, edits if needed, and approves before sending.', 'color' => 'amber'],
            ['type' => 'output',   'label' => 'Send & Log',             'description' => 'Sends via email/LinkedIn and updates the CRM with all enrichment data.', 'color' => 'green'],
        ],
        'metrics' => [
            ['number' => '5×',   'label' => 'More prospects reached',  'description' => 'Same SDR team, dramatically higher outbound volume.'],
            ['number' => '3×',   'label' => 'Higher reply rates',       'description' => 'Personalised context outperforms generic templates.'],
            ['number' => '90%',  'label' => 'Less manual research',     'description' => 'Research Agent handles enrichment end to end.'],
        ],
        'faqs' => [
            ['question' => 'Which CRM and outreach tools does FleetQ integrate with?', 'answer' => 'FleetQ integrates via webhook, REST API, and MCP tools — connecting to HubSpot, Salesforce, Pipedrive, and outreach platforms like Apollo, Lemlist, or custom email flows.'],
            ['question' => 'How does the Research Agent enrich leads?', 'answer' => 'The Research Agent uses web search, LinkedIn scraping tools, and news feeds to gather company information, recent announcements, and contact details — automatically.'],
            ['question' => 'Can I define my own ICP scoring criteria?', 'answer' => 'Yes. Create a qualification skill that encodes your Ideal Customer Profile criteria. The Qualifier Agent uses this skill to score every lead on a consistent rubric.'],
            ['question' => 'What if a lead fails qualification?', 'answer' => 'Disqualified leads are automatically tagged in the CRM and excluded from outreach. You can configure the workflow to send them to a nurture sequence instead.'],
            ['question' => 'Is the outreach compliant with GDPR and CAN-SPAM?', 'answer' => 'FleetQ\'s guardrail skills include PII detection. You are responsible for ensuring your outreach lists and messaging comply with applicable regulations in your markets.'],
        ],
        'capabilities' => [
            ['label' => 'Signal Connectors', 'desc' => 'Ingest leads from forms, CSVs, and CRM webhooks.', 'route' => 'register'],
            ['label' => 'AI Agent Crews', 'desc' => 'Research, Qualify, and Personalise in sequence.', 'route' => 'register'],
            ['label' => 'Skills Library', 'desc' => 'ICP scoring, outreach writing, and CRM update skills.', 'route' => 'register'],
            ['label' => 'Approval Gates', 'desc' => 'SDR reviews personalised drafts before send.', 'route' => 'register'],
            ['label' => 'MCP Tool Integration', 'desc' => 'Connect to CRMs, email platforms, and LinkedIn tools.', 'route' => 'register'],
            ['label' => 'Audit Trail', 'desc' => 'Every lead action logged for pipeline reporting.', 'route' => 'register'],
        ],
        'related' => ['content-marketing', 'data-research', 'customer-support'],
    ],

    'data-research' => [
        'meta_title' => 'AI Agents for Data Research & Competitive Intelligence | FleetQ',
        'meta_description' => 'Deploy AI crews that monitor competitors, aggregate data from multiple sources, and deliver synthesised reports automatically. Build with FleetQ.',
        'keywords' => 'ai research automation, competitive intelligence agent, ai data pipeline, ai market research, automated competitive analysis',
        'title_short' => 'Data Research',
        'icon_color' => 'orange',
        'accent' => 'border-t-orange-400',
        'icon_bg' => 'bg-orange-50',
        'icon_text' => 'text-orange-600',
        'heading' => 'Deploy AI Crews That Monitor, Aggregate, and Synthesize Data',
        'subheading' => 'AI agent crews that watch your competitive landscape, aggregate data from dozens of sources, and deliver structured intelligence reports — on demand or on schedule.',
        'pain_points' => [
            'Competitive monitoring requires checking dozens of sources manually — a task too time-consuming to do consistently.',
            'Analysts spend more time collecting data than interpreting it.',
            'Important signals — a competitor\'s pricing change, a regulatory update — are missed because no one is watching 24/7.',
            'Raw data from multiple sources arrives in different formats, requiring manual normalisation before analysis.',
        ],
        'workflow_steps' => [
            ['type' => 'signal',   'label' => 'Trigger',           'description' => 'Scheduled trigger, webhook, or manual kick-off starts the research run.', 'color' => 'blue'],
            ['type' => 'agent',    'label' => 'Monitor Agent',     'description' => 'Scans configured sources: web, RSS feeds, news APIs, and social channels.', 'color' => 'primary'],
            ['type' => 'agent',    'label' => 'Extractor Agent',   'description' => 'Pulls structured data from raw sources and normalises it into a consistent schema.', 'color' => 'primary'],
            ['type' => 'agent',    'label' => 'Analyst Agent',     'description' => 'Identifies trends, anomalies, and noteworthy signals from the aggregated data.', 'color' => 'violet'],
            ['type' => 'agent',    'label' => 'Synthesiser Agent', 'description' => 'Writes a structured intelligence brief with findings, implications, and next steps.', 'color' => 'violet'],
            ['type' => 'output',   'label' => 'Deliver Report',    'description' => 'Sends the report via email, Slack, Telegram, or stores it in your knowledge base.', 'color' => 'green'],
        ],
        'metrics' => [
            ['number' => '24/7', 'label' => 'Market monitoring',      'description' => 'Agents never sleep — every competitor move captured in real time.'],
            ['number' => '40+',  'label' => 'Sources per report',      'description' => 'Aggregates data from news, web, social, and internal sources simultaneously.'],
            ['number' => '90%',  'label' => 'Faster time to insight',  'description' => 'Analysts spend time on strategy, not data collection.'],
        ],
        'faqs' => [
            ['question' => 'What sources can the Monitor Agent watch?', 'answer' => 'RSS feeds, web pages (via scraping tools), news APIs, social media, GitHub repositories, job boards, and any source accessible via HTTP. You configure the sources per workflow.'],
            ['question' => 'How often can I run research workflows?', 'answer' => 'Continuously. FleetQ supports event-driven triggers (a competitor publishes a new blog post), scheduled runs (every 6 hours), and manual kick-offs from the dashboard or MCP.'],
            ['question' => 'Can the crew track specific companies or keywords?', 'answer' => 'Yes. Define your target entities — competitor names, product names, keywords — as parameters in the workflow. The Monitor Agent focuses exclusively on those targets.'],
            ['question' => 'How are reports delivered?', 'answer' => 'Via email, Slack webhook, Telegram bot, or any outbound connector. You can also store reports as versioned artifacts in FleetQ for historical comparison.'],
            ['question' => 'Can I compare reports over time to spot trends?', 'answer' => 'Yes. FleetQ stores every research run as an artifact. The Analyst Agent can be given historical context from previous runs to produce trend analysis in addition to point-in-time reporting.'],
        ],
        'capabilities' => [
            ['label' => 'Signal Connectors', 'desc' => 'RSS, webhook, and scheduled triggers for monitoring.', 'route' => 'register'],
            ['label' => 'AI Agent Crews', 'desc' => 'Monitor, Extract, Analyse, and Synthesise agents.', 'route' => 'register'],
            ['label' => 'Project Scheduling', 'desc' => 'Schedule recurring research runs automatically.', 'route' => 'register'],
            ['label' => 'Artifact Storage', 'desc' => 'Store and version every report for historical comparison.', 'route' => 'register'],
            ['label' => 'Outbound Connectors', 'desc' => 'Deliver reports via email, Slack, or Telegram.', 'route' => 'register'],
            ['label' => 'MCP Tool Integration', 'desc' => 'Scrape and aggregate from any web source.', 'route' => 'register'],
        ],
        'related' => ['content-marketing', 'software-development', 'compliance-monitoring'],
    ],

    'software-development' => [
        'meta_title' => 'AI Agents for Software Development Workflows | FleetQ',
        'meta_description' => 'Automate code review, test generation, and PR workflows with AI agent crews. Ship faster with AI-assisted development workflows. Build with FleetQ.',
        'keywords' => 'ai code review automation, automated testing agent, ai dev workflow, ai software development, code review ai crew',
        'title_short' => 'Software Development',
        'icon_color' => 'indigo',
        'accent' => 'border-t-indigo-400',
        'icon_bg' => 'bg-indigo-50',
        'icon_text' => 'text-indigo-600',
        'heading' => 'AI Agents That Review Code, Write Tests, and Ship Faster',
        'subheading' => 'AI agent crews that give every pull request a thorough code review, generate missing tests, and enforce engineering standards — without slowing down your team.',
        'pain_points' => [
            'Code reviews create bottlenecks — PRs sit waiting for senior engineers who are already stretched.',
            'Test coverage is inconsistent across the codebase because writing tests is time-consuming and often deprioritised.',
            'Engineering standards and best practices drift as teams grow and onboarding is informal.',
            'Context switching between writing code and reviewing others\' work kills developer deep work time.',
        ],
        'workflow_steps' => [
            ['type' => 'signal',   'label' => 'PR Opened',              'description' => 'A pull request is opened on GitHub/GitLab, triggering the review crew via webhook.', 'color' => 'blue'],
            ['type' => 'agent',    'label' => 'Review Agent',            'description' => 'Analyses the diff for bugs, security issues, performance problems, and style violations.', 'color' => 'primary'],
            ['type' => 'agent',    'label' => 'Test Generator Agent',    'description' => 'Writes missing unit and integration tests for the changed code.', 'color' => 'primary'],
            ['type' => 'agent',    'label' => 'Docs Agent',              'description' => 'Updates inline documentation and changelogs to reflect the changes.', 'color' => 'violet'],
            ['type' => 'approval', 'label' => 'Engineer Sign-off',       'description' => 'A human engineer reviews the AI feedback and generated tests before merge.', 'color' => 'amber'],
            ['type' => 'output',   'label' => 'Merge & Notify',          'description' => 'Approves the PR, posts review summary, and notifies the team via Slack or Telegram.', 'color' => 'green'],
        ],
        'metrics' => [
            ['number' => '70%',  'label' => 'Faster PR review',      'description' => 'AI first-pass review reduces time before human engineer review.'],
            ['number' => '3×',   'label' => 'More test coverage',    'description' => 'Test Generator Agent fills gaps automatically on every PR.'],
            ['number' => '0',    'label' => 'Missed style issues',    'description' => 'Every PR checked against your engineering standards consistently.'],
        ],
        'faqs' => [
            ['question' => 'Which version control platforms are supported?', 'answer' => 'Any platform with webhook support — GitHub, GitLab, Bitbucket, and Azure DevOps. The webhook connector receives the PR event and the agent crew takes it from there.'],
            ['question' => 'Can I define custom review rules and standards?', 'answer' => 'Yes. Create a "Engineering Standards" skill with your team\'s rules. The Review Agent uses this skill to check every PR against your specific guidelines, not just generic best practices.'],
            ['question' => 'What languages does the Review Agent support?', 'answer' => 'Any language that the underlying LLM understands — including Python, JavaScript/TypeScript, Ruby, Go, Java, PHP, Rust, and more. The skill defines the language context.'],
            ['question' => 'Do the generated tests need human review?', 'answer' => 'Yes, the approval gate catches this. The Test Generator Agent\'s output goes through engineer sign-off before any code is committed. The agents assist, they don\'t bypass your process.'],
            ['question' => 'Can I run this on a self-hosted FleetQ instance?', 'answer' => 'Absolutely. FleetQ is open source and self-hostable. Your code never leaves your infrastructure — agents access GitHub/GitLab via API tokens that you control.'],
        ],
        'capabilities' => [
            ['label' => 'Signal Connectors', 'desc' => 'Trigger workflows from GitHub/GitLab webhooks.', 'route' => 'register'],
            ['label' => 'AI Agent Crews', 'desc' => 'Review, Test Generation, and Docs agents in sequence.', 'route' => 'register'],
            ['label' => 'Skills Library', 'desc' => 'Encode your engineering standards as reusable skills.', 'route' => 'register'],
            ['label' => 'Approval Gates', 'desc' => 'Engineer sign-off required before any merge action.', 'route' => 'register'],
            ['label' => 'MCP Tool Integration', 'desc' => 'Connect to GitHub APIs, CI systems, and code analysis tools.', 'route' => 'register'],
            ['label' => 'Outbound Connectors', 'desc' => 'Notify teams via Slack, Telegram, or email.', 'route' => 'register'],
        ],
        'related' => ['data-research', 'compliance-monitoring', 'content-marketing'],
    ],

    'compliance-monitoring' => [
        'meta_title' => 'AI Agents for Compliance Monitoring & Risk Detection | FleetQ',
        'meta_description' => 'Automate regulatory compliance checks with AI agent crews that monitor, classify, and alert on risks 24/7. Build compliant AI workflows with FleetQ.',
        'keywords' => 'ai compliance monitoring, automated risk detection, regulatory alert agent, ai risk management, compliance automation ai',
        'title_short' => 'Compliance Monitoring',
        'icon_color' => 'red',
        'accent' => 'border-t-red-400',
        'icon_bg' => 'bg-red-50',
        'icon_text' => 'text-red-600',
        'heading' => 'Automate Compliance Checks with AI Agents That Never Sleep',
        'subheading' => 'AI agent crews that continuously monitor regulatory changes, classify risk events, escalate findings to the right humans, and maintain a full audit trail — automatically.',
        'pain_points' => [
            'Regulatory requirements change faster than manual review processes can keep up.',
            'Compliance teams are overwhelmed with monitoring alerts — most are false positives requiring manual triage.',
            'Audit preparation is reactive: evidence is gathered after the fact rather than captured continuously.',
            'Inconsistent application of compliance rules across different teams and geographies creates gaps.',
        ],
        'workflow_steps' => [
            ['type' => 'signal',   'label' => 'Regulatory Event',   'description' => 'A new regulation, policy update, or internal event triggers the monitoring crew.', 'color' => 'blue'],
            ['type' => 'agent',    'label' => 'Monitor Agent',       'description' => 'Watches regulatory feeds, legal databases, and internal systems for relevant changes.', 'color' => 'primary'],
            ['type' => 'agent',    'label' => 'Risk Classifier',     'description' => 'Assesses the risk level of each event: low, medium, high, or critical.', 'color' => 'primary'],
            ['type' => 'agent',    'label' => 'Impact Analyst',      'description' => 'Maps the regulatory change to affected processes, products, or jurisdictions.', 'color' => 'violet'],
            ['type' => 'approval', 'label' => 'Compliance Review',   'description' => 'High and critical risks are routed to a compliance officer for human judgment.', 'color' => 'amber'],
            ['type' => 'output',   'label' => 'Audit Log & Alert',   'description' => 'Logs the event with full reasoning, sends alerts, and updates the compliance register.', 'color' => 'green'],
        ],
        'metrics' => [
            ['number' => '24/7', 'label' => 'Regulatory monitoring', 'description' => 'No compliance event goes undetected, regardless of time zone.'],
            ['number' => '80%',  'label' => 'Fewer false positives',  'description' => 'Risk Classifier pre-filters noise before escalating to humans.'],
            ['number' => '100%', 'label' => 'Audit evidence capture', 'description' => 'Every decision logged continuously for audit readiness.'],
        ],
        'faqs' => [
            ['question' => 'Which regulatory frameworks does this support?', 'answer' => 'FleetQ is framework-agnostic. You define the rules via skills — GDPR, CCPA, SOC 2, ISO 27001, HIPAA, or any internal policy. The agents apply whatever you configure.'],
            ['question' => 'Where does the Monitor Agent watch for regulatory changes?', 'answer' => 'RSS feeds from regulatory bodies, government legal databases, legal news services, and any source accessible via HTTP. You configure the specific feeds relevant to your jurisdictions.'],
            ['question' => 'How do human reviewers receive escalations?', 'answer' => 'Via the approval inbox in the FleetQ dashboard, email notification, Slack message, or Telegram. The compliance officer sees the AI\'s risk assessment and evidence before making a decision.'],
            ['question' => 'Is the audit trail tamper-evident?', 'answer' => 'FleetQ\'s audit log records every event with a timestamp and the agent\'s reasoning. The log is append-only and can be exported for external audit systems.'],
            ['question' => 'Can this run alongside an existing GRC tool?', 'answer' => 'Yes. FleetQ integrates with external tools via API and webhook. You can push findings to your existing GRC platform while using FleetQ for the monitoring and triage workflow.'],
        ],
        'capabilities' => [
            ['label' => 'Signal Connectors', 'desc' => 'Monitor regulatory feeds, news, and internal systems.', 'route' => 'register'],
            ['label' => 'AI Guardrails', 'desc' => 'PII and sensitive data checks built into every workflow.', 'route' => 'register'],
            ['label' => 'Approval Gates', 'desc' => 'High-risk findings escalate to human compliance officers.', 'route' => 'register'],
            ['label' => 'Audit Trail', 'desc' => 'Full, append-only log of every agent decision and reasoning.', 'route' => 'register'],
            ['label' => 'Outbound Connectors', 'desc' => 'Alert via email, Slack, Telegram, or webhook to GRC tools.', 'route' => 'register'],
            ['label' => 'Budget Controls', 'desc' => 'Set spend limits per monitoring workflow.', 'route' => 'register'],
        ],
        'related' => ['data-research', 'customer-support', 'finance-reporting'],
    ],

    'hr-recruiting' => [
        'meta_title' => 'AI Agent Crews for Recruiting & HR Automation | FleetQ',
        'meta_description' => 'Automate resume screening, candidate scoring, and interview scheduling with AI agent crews. Build faster recruiting pipelines with FleetQ.',
        'keywords' => 'ai recruiting automation, resume screening agent, candidate workflow ai, ai hiring, automated recruitment ai crew',
        'title_short' => 'HR & Recruiting',
        'icon_color' => 'teal',
        'accent' => 'border-t-teal-400',
        'icon_bg' => 'bg-teal-50',
        'icon_text' => 'text-teal-600',
        'heading' => 'AI Crews That Screen, Score, and Schedule Recruiting Pipelines',
        'subheading' => 'Automate the repetitive stages of recruiting — application screening, skills assessment, and interview scheduling — so your HR team focuses on candidate relationships.',
        'pain_points' => [
            'High application volumes make it impossible to give every candidate a fair, thorough review.',
            'Screening criteria are applied inconsistently — different recruiters weigh the same skills differently.',
            'Scheduling interviews requires multiple back-and-forth emails, wasting recruiter and candidate time.',
            'Top candidates drop out of slow pipelines while waiting for feedback from overloaded HR teams.',
        ],
        'workflow_steps' => [
            ['type' => 'signal',   'label' => 'Application Received', 'description' => 'A new application arrives via ATS webhook, email, or form connector.', 'color' => 'blue'],
            ['type' => 'agent',    'label' => 'Screener Agent',        'description' => 'Reviews resume and cover letter against the role requirements and must-have criteria.', 'color' => 'primary'],
            ['type' => 'agent',    'label' => 'Scorer Agent',          'description' => 'Assigns a fit score across skills, experience, and culture indicators.', 'color' => 'primary'],
            ['type' => 'approval', 'label' => 'Recruiter Review',      'description' => 'Recruiter sees the AI scorecard and decides: advance, reject, or flag for discussion.', 'color' => 'amber'],
            ['type' => 'agent',    'label' => 'Scheduler Agent',       'description' => 'Sends the candidate a personalised outreach and books the interview slot.', 'color' => 'violet'],
            ['type' => 'output',   'label' => 'Notify & Log',          'description' => 'Updates the ATS, notifies the hiring manager, and logs the screening decision.', 'color' => 'green'],
        ],
        'metrics' => [
            ['number' => '5×',   'label' => 'Candidates processed',    'description' => 'Screen the same number of applications with a fraction of the recruiter hours.'],
            ['number' => '60%',  'label' => 'Faster time-to-interview', 'description' => 'Top candidates advance in days, not weeks.'],
            ['number' => '100%', 'label' => 'Consistent scoring',       'description' => 'Every candidate evaluated against the same criteria every time.'],
        ],
        'faqs' => [
            ['question' => 'Which ATS platforms does this integrate with?', 'answer' => 'Any ATS with webhook or API support — Greenhouse, Lever, Workday, BambooHR, and others. The Signal Connector handles application ingestion from your current system.'],
            ['question' => 'How are screening criteria defined?', 'answer' => 'Create a "Role Requirements" skill for each position. The Screener and Scorer agents use this skill so every candidate is evaluated against the same documented criteria — not individual recruiter judgment.'],
            ['question' => 'Can recruiters override the AI score?', 'answer' => 'Yes. The recruiter approval gate shows the AI scorecard and reasoning. Recruiters can advance or reject regardless of the AI score, and their decision and reasoning are logged.'],
            ['question' => 'How does the Scheduler Agent book interviews?', 'answer' => 'Via calendar integration (Google Calendar, Outlook) or a scheduling tool like Calendly. The agent sends the candidate a personalised message with a booking link.'],
            ['question' => 'Is this compliant with employment discrimination law?', 'answer' => 'FleetQ\'s guardrail skills can be configured to flag and exclude protected characteristics from scoring. Compliance with employment law is your responsibility — the platform provides the tooling to apply consistent, documented criteria.'],
        ],
        'capabilities' => [
            ['label' => 'Signal Connectors', 'desc' => 'Ingest applications from ATS, email, or forms.', 'route' => 'register'],
            ['label' => 'AI Agent Crews', 'desc' => 'Screener and Scorer agents with consistent criteria.', 'route' => 'register'],
            ['label' => 'Skills Library', 'desc' => 'Role-specific screening rubrics as reusable skills.', 'route' => 'register'],
            ['label' => 'Approval Gates', 'desc' => 'Recruiter decision required before advancing candidates.', 'route' => 'register'],
            ['label' => 'AI Guardrails', 'desc' => 'Filter protected characteristics from scoring inputs.', 'route' => 'register'],
            ['label' => 'Audit Trail', 'desc' => 'Every screening decision logged for compliance evidence.', 'route' => 'register'],
        ],
        'related' => ['customer-support', 'compliance-monitoring', 'finance-reporting'],
    ],

    'finance-reporting' => [
        'meta_title' => 'AI Agents for Finance Automation & Reporting | FleetQ',
        'meta_description' => 'Automate financial data collection, validation, and report generation with AI agent crews. Close your books faster with FleetQ.',
        'keywords' => 'ai finance automation, automated financial reporting, accounting ai agent, ai bookkeeping, financial data pipeline ai',
        'title_short' => 'Finance & Reporting',
        'icon_color' => 'emerald',
        'accent' => 'border-t-emerald-400',
        'icon_bg' => 'bg-emerald-50',
        'icon_text' => 'text-emerald-600',
        'heading' => 'Automate Financial Data Collection and Reporting with AI Agents',
        'subheading' => 'AI agent crews that collect data from multiple sources, validate it, detect anomalies, and produce structured financial reports — with human sign-off at every critical step.',
        'pain_points' => [
            'Month-end close involves manually pulling data from a dozen different systems — ERP, bank feeds, expense tools.',
            'Data validation is error-prone when done manually at scale across hundreds of line items.',
            'Finance teams spend most of their time on data wrangling, not on analysis and insight.',
            'Financial reports take days to prepare because each step depends on the previous one completing.',
        ],
        'workflow_steps' => [
            ['type' => 'signal',   'label' => 'Reporting Trigger',   'description' => 'Scheduled trigger or manual kick-off starts the monthly close workflow.', 'color' => 'blue'],
            ['type' => 'agent',    'label' => 'Collector Agent',      'description' => 'Pulls data from connected systems: ERP, bank feeds, expense tools, invoicing platforms.', 'color' => 'primary'],
            ['type' => 'agent',    'label' => 'Validator Agent',      'description' => 'Checks for missing entries, duplicates, and rule violations. Flags anomalies for review.', 'color' => 'primary'],
            ['type' => 'agent',    'label' => 'Analyser Agent',       'description' => 'Calculates KPIs, compares to budget, and identifies variance drivers.', 'color' => 'violet'],
            ['type' => 'approval', 'label' => 'CFO Sign-off',         'description' => 'Finance lead reviews the AI-generated analysis before the report is finalised.', 'color' => 'amber'],
            ['type' => 'output',   'label' => 'Publish Report',       'description' => 'Produces the final report in your preferred format and distributes to stakeholders.', 'color' => 'green'],
        ],
        'metrics' => [
            ['number' => '3×',   'label' => 'Faster month-end close', 'description' => 'Data collection and validation completed in hours, not days.'],
            ['number' => '99%',  'label' => 'Data accuracy',           'description' => 'Validator Agent catches anomalies and errors before they reach the report.'],
            ['number' => '80%',  'label' => 'Less manual work',        'description' => 'Finance team focuses on analysis and decisions, not data gathering.'],
        ],
        'faqs' => [
            ['question' => 'Which financial systems can the Collector Agent connect to?', 'answer' => 'Any system with an API or webhook — QuickBooks, Xero, NetSuite, Stripe, bank feeds via Open Banking, expense platforms like Expensify or Spendesk, and payroll systems.'],
            ['question' => 'How does the Validator Agent detect anomalies?', 'answer' => 'You define validation rules in a skill — expected ranges, reconciliation checks, duplicate detection logic. The agent applies these rules consistently to every data set.'],
            ['question' => 'Can I build custom KPI calculations?', 'answer' => 'Yes. Create an "Analytics" skill with your specific KPI formulas and reporting structure. The Analyser Agent uses this skill so your reports always follow the same methodology.'],
            ['question' => 'Who can see the financial data being processed?', 'answer' => 'Only users with the appropriate role in your FleetQ team. All processing happens in your self-hosted or cloud environment — your financial data does not leave your infrastructure.'],
            ['question' => 'Can the report be distributed automatically after CFO approval?', 'answer' => 'Yes. After the approval gate is cleared, the Publish Agent can send the report via email, Slack, or store it in a designated SharePoint/Google Drive folder via webhook integration.'],
        ],
        'capabilities' => [
            ['label' => 'Project Scheduling', 'desc' => 'Trigger monthly close workflows automatically.', 'route' => 'register'],
            ['label' => 'AI Agent Crews', 'desc' => 'Collector, Validator, and Analyser agents in sequence.', 'route' => 'register'],
            ['label' => 'Skills Library', 'desc' => 'KPI formulas, validation rules, and reporting templates.', 'route' => 'register'],
            ['label' => 'Approval Gates', 'desc' => 'CFO review required before report is finalised.', 'route' => 'register'],
            ['label' => 'Audit Trail', 'desc' => 'Every data collection and validation step logged.', 'route' => 'register'],
            ['label' => 'Outbound Connectors', 'desc' => 'Distribute reports via email, Slack, or file storage.', 'route' => 'register'],
        ],
        'related' => ['compliance-monitoring', 'data-research', 'hr-recruiting'],
    ],

];
